trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

steps:

- checkout: self

- script: ls -la
  displayName: 'List Files'

# Check Java
- script: java -version
  displayName: 'Check Java'

# Check Dotnet
- script: dotnet --version
  displayName: 'Check Dotnet'

# Check Maven
- script: mvn -version
  displayName: 'Check Maven'

# Maven Build
- script: |
    cd simple-maven-project
    mvn clean verify
  displayName: 'Build with Maven'

# Grant Permission
- script: chmod +x run-quality.sh
  displayName: 'Grant Permission'

# Run Quality Script
- script: ./run-quality.sh
  displayName: 'Run Quality Script'
