trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- script: ls -la
  displayName: 'List Files'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: UseDotNet@2
  inputs:
    version: '8.0.x'

- script: |
    cd simple-maven-project
    mvn clean verify
  displayName: 'Build with Maven'

- script: chmod +x run-quality.sh
  displayName: 'Grant Permission'

- script: ./run-quality.sh
  displayName: 'Run Quality Script'
