trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

resources:
  repositories:
    - repository: qualityTemplates
      type: github
      name: AnjaliSingh0310/gitrepo
      endpoint: AnjaliSingh0310

jobs:
- job: EnvironmentCheck
  displayName: Check Build Environment
  steps:
    - checkout: self

    - script: ls -la
      displayName: List Files

    - script: java -version
      displayName: Check Java

    - script: dotnet --version
      displayName: Check Dotnet

    - script: mvn -version
      displayName: Check Maven

- job: Build
  displayName: Run Extension Build
  dependsOn: EnvironmentCheck
  steps:
    - task: RunQuality@1
      inputs:
        projectKey: AnjaliSingh0310_gitrepo
        organization: anjalisingh0310
        solution: 'eShopOnWeb/eShopOnWeb.sln'
        coveragePath: eShopOnWeb/tests/**/coverage.cobertura.xml
        sonarToken: 33f49840787e6388b6ceab0e11da146d09902636