trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

jobs:
- job: Build
  displayName: Run Cavisson Analyzer
  steps:        
      - task: CavissonAnalyzerProjects@1
        inputs:
          cavissonAnalyzerServiceConnection: 'CS'
          project: 'a4'

    
    

      

      
