trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

jobs:
- job: Build
  displayName: Run Extension Build
  steps:
    - task: run-quality@1
      inputs:
        projectKey: my_unique_testing_key
        organization: ''
        hostUrl: 'https://sonar.cav-test.com:4444/sonar'
        solution: 'eShopOnWeb/eShopOnWeb.sln'
        coveragePath: eShopOnWeb/tests/**/coverage.cobertura.xml
        sonarToken: sqp_5c9379989cc54d0e4f8777cba7293437101c1074