trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

jobs:
- job: Build
  displayName: Run Extension Build
  steps:        
      - task: CavissonAnalyzerProjects@1
        inputs:
          cavissonAnalyzerServiceConnection: 'caaa'
          project: 'a1'

    
    

      

      
