trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

jobs:
- job: Build
  displayName: Run Extension Build
  steps:
    - task: CavissonScanProjects@1
      inputs:
        cavissonScannerServiceConnection: 's'
        project: 'cavisson_proj_cav_Anjali_01'
    