trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

jobs:
- job: Build
  displayName: Run Extension Build
  steps:
    - task: cavisson-scanner@1
      inputs:
        project: cavisson_proj_cav
        reportServerUrl: 'https://sonar.cav-test.com:4444/code_analyzer'
        reportAccessToken: squ_d474dcc4e682bac749e96222088596a3cdc7e09b