trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

resources:
  repositories:
    - repository: qualityTemplates
      type: git
      name: gitrepo/azure-quality-templates

jobs:
- job: EnvironmentCheck
  displayName: Check Build Environment
  steps:
    - checkout: self

    - script: ls -la
      displayName: List Files

    - script: java -version
      displayName: Check Java

    - script: dotnet --version
      displayName: Check Dotnet

    - script: mvn -version
      displayName: Check Maven


- job: CodeQuality
  displayName: Run Sonar Quality
  dependsOn: EnvironmentCheck
  steps:
    - checkout: self
    - checkout: qualityTemplates

    - template: templates/run-quality.yml@qualityTemplates
      parameters:
        projectKey: AnjaliSingh0310_gitrepo
        organization: anjalisingh0310
        solution: eShopOnWeb/eShopOnWeb.sln
        coveragePath: eShopOnWeb/tests/**/coverage.cobertura.xml
        sonarToken: 33f49840787e6388b6ceab0e11da146d09902636