/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 02/10/2026 04:24:34
    Flow details:
    Build details: 4.14.1 (build# 46)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{

        ns_start_transaction("url_test_method");
        ns_web_url("url_test_method",
            "URL=http://127.0.0.1:7912/url_service/url_test.xml?SvcTime=150&Status=200",
	        "HEADER=Accept-Encoding:gzip, deflate, br",
            "HEADER=Accept-Language:en-US,en;q=0.9",
         );
        ns_end_transaction("url_test_method", NS_AUTO_STATUS);

        ns_page_think_time(1);

        ns_start_transaction("url_test_page");
        ns_web_url("url_test_page",
            "URL=http://127.0.0.1:7912/url_service/url_test.xml?SvcTime=150&Status=200",
            "METHOD=POST",
	        "HEADER=Accept-Encoding:gzip, deflate, br",
            "HEADER=Accept-Language:en-US,en;q=0.9",
            BODY_BEGIN,
            "Write your POST Body Content Here"
            BODY_END
         );
        ns_end_transaction("url_test_page", NS_AUTO_STATUS);
        ns_page_think_time(1);

}
