#!/bin/bash

source $NS_WDIR/TSDB/tsdb/automation/testsuites/common
common_setup

# Expected graph are those which we are getting from response 
expected_graphs() 
{
   mg="$1"
   mg_id="$2"
   Response="$3"
   cat $Response | grep 'name:' | tail -n+3 | cut -d':' -f2 > ${GROUP_GRAPH_TEMP}/.expected_grph
   #sed -i 's/[[:blank:]]*//' ${GROUP_GRAPH_TEMP}/.expected_graphs
   >${GROUP_GRAPH_TEMP}/.expected_graphs
   while IFS= read -r line; do
      trimmed_line="${line#"${line%%[![:space:]]*}"}"
      echo "$trimmed_line" >> "${GROUP_GRAPH_TEMP}/.expected_graphs"
   done < ${GROUP_GRAPH_TEMP}/.expected_grph
   automation_log "Response=$Response"
}

# ACTUAL graph are those which we are getting from gdf file .
actual_graphs() 
{
   mg="$1"
   mg_id="$2"
   gdf_name=`grep "|$1|" $NS_WDIR/sys/*.gdf | cut -d':' -f1 | cut -d'/' -f6`
   num_graphs=`grep "|$1|" $NS_WDIR/sys/*.gdf |  cut -d'|' -f5`
   cat $NS_WDIR/sys/$gdf_name | grep "^Graph|" | cut -d'|' -f2 > ${GROUP_GRAPH_TEMP}/.actual_graphs
   automation_log "gdf_name=$gdf_name"
   automation_log "num_graphs=$num_graphs"
   virtual_metric=$(cat $NS_WDIR/sys/$gdf_name | cut -d'|' -f13 | grep "(" )
   grep "$virtual_metric" $NS_WDIR/sys/$gdf_name | cut -d'|' -f2 > ${GROUP_GRAPH_TEMP}/.virtual_graphs
   ${GROUP_GRAPH_TEMP}/.virtual_graphs >> ${GROUP_GRAPH_TEMP}/.actual_graphs
}

validate_virtual_graphs()
{
   while IFS=read -r line;
   do
      if [ $(grep -c "$line" ${GROUP_GRAPH_TEMP}/.expected_graphs) -gt 2 ];then
         ERR_MSG=$ERR_MSG"Repeated virtual graphs - $line "
      fi
   done < ${GROUP_GRAPH_TEMP}/.virtual_graphs
}

validate_graphs()
{
   expected_graphs "$1" "$2" "$3"
   actual_graphs "$1" "$2" 
   validate_virtual_graphs

   #checks the file line number in both expected and actual file
   while IFS=read -r line;
   do
     if [ $(grep -c "$line" ${GROUP_GRAPH_TEMP}/.expected_graphs) -eq 0 ];then
        ERR_MSG=$ERR_MSG"Wrong graphs - $line "
     fi
   done < ${GROUP_GRAPH_TEMP}/.actual_graphs


   
   #sed -i "s/ /\n/g" ${GROUP_GRAPH_TEMP}/.expected_graphs
   #sed -i "s/ /\n/g" ${GROUP_GRAPH_TEMP}/.actual_graphs


   file1="${GROUP_GRAPH_TEMP}/.expected_graphs"
   file2="${GROUP_GRAPH_TEMP}/.actual_graphs"

   # Read the content of file1
   file1_content=$(cat "$file1")

    # Check if file2 contains the content of file1
    if grep -qF "$file1_content" "$file2"; then
      automation_log "File 1 content is present in File 2."
    else
      automation_log "File 1 content is not present in File 2."
      ERR_MSG=$ERR_MSG"Wrong graphs - $file1_content"
    fi


   if [ ${#ERR_MSG} -gt 0 ];then
      result1="FAIL"
   else
      result1="PASS"
   fi

   if [ "$result1" == "FAIL" ];then
      echo "$ERR_MSG"
   else
      echo "PASS"
   fi

}
