#!/bin/bash

TS_NAME=""
TS_IDX=0

if [ "X$1" != "X" ]; then
  TS_NAME=$1;
  if [ "$TS_NAME" != "all" ]; then
    TS_NAME=`echo $TS_NAME.bats`
  fi
  echo "Given testsuite name $TS_NAME"
fi

python3 -m pip install requirements.txt >logs/requirements.log
testsuites=($(ls -ltrh ./testsuites | grep ".bats$" | awk '{print $NF}' | awk -F'/' '{print $NF}' | xargs) all)
len=${#testsuites[@]}

if [ "$TS_NAME" != "all" ]; then
  echo -e "Select testsuite to run :\n"

  for ((i=0; i<len; i++))
  do
    echo "[$((i+1))]${testsuites[i]}"
    if [ "$TS_NAME" != "" ] && [ "$TS_NAME" == ${testsuites[i]} ]; then
      TS_IDX=$((i+1));
      #break;
    fi
  done
else
  TS_IDX=$len;
fi

echo -e "\n"
if [ $TS_IDX -eq 0 ]; then
  read option
  idx=$((option - 1))
else
  idx=$((TS_IDX - 1))
fi


if [ $idx -eq -1 ]; then
  echo "[*] Invalid option of testsuite"
  exit
else
  echo "[*] Going to Trigger No. $((idx + 1)) testsuite"
fi

if [ ${testsuites[idx]} == "all" ];then
   ./thirdparty/bats-core/bin/bats testsuites/*.bats --report-formatter junit -o .
else
   ./thirdparty/bats-core/bin/bats testsuites/${testsuites[idx]} --report-formatter junit -o .
fi
python3 ./lib/xmltohtml.py
