/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: Rajat
    Date of generation: 12/31/2020 06:21:41
    Flow details:
    Build details: 4.5.0 (build# 62)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int init_script()
{
    return 0;
}
