/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 05/25/2012 04:15:00
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tslb_cdigest.h"
#include "ns_string.h"
#include "flow_util.c"

//Control connections related functions
int make_control_conn_with_ndc(char *ndc_ip,  char *ndc_port)
{ 
  char uri[64 + 1];
  int ret_val = -1; 
  int count = 0;

  snprintf(uri, 64, "%s:%s", ndc_ip, ndc_port);
  if(debug_level >= 1)
  fprintf (stderr, "\n*** message  created %s\n", uri);
  if(debug_level >= 1)
  fprintf(stderr, "*** ndc_ip =%s, ndc_port= %s \n",ndc_ip, ndc_port);
                                         
  ns_save_string(uri, "ndagent2ndc");       
    
  while(1)
  { 
    ns_start_transaction("NDAgentControlConnection");
      ret_val = ns_web_websocket_connect("ID=1",
                                         "URI=ws://{ndagent2ndc}/",
                                         "Origin=http://127.0.0.1",
                                         "Header=Accept-Language:en-us,en;q=0.5");


    if(ret_val != 0)
    {
      fprintf (stderr, "**Unable to connect with ndc server with ip %s and port\n", ndc_ip, ndc_port);

      if(count == 10)
      {
        ns_end_transaction("NDAgentControlConnection", NS_AUTO_STATUS);
        return ret_val;
      }
    }
    else
    {
      if(debug_level >= 1)    	
      fprintf (stderr , "*** Successfully connect with ndc server with ip %s and port %s ***\n", ndc_ip, ndc_port);
      ns_end_transaction("NDAgentControlConnection", NS_AUTO_STATUS);
      return ret_val;
    }
    ns_page_think_time(10);
    count++;
  }

  return ret_val;
}

int send_control_conn_request_to_ndc(char *app_name, char *nd_app_server_host, char *tier_name, char *bci_start_time, char *bci_timestamp, char *bci_pid, char *server_ip, char *hostname, char *last_connection_time_stamp)
{
  int  ret_val = -1;

  char ndagent_req[2048 + 1];

 // if(debug_level >= 1)
  fprintf(stderr, "**** app_name = [%s], nd_app_server_host = [%s], tier_name = [%s], bci_start_time = [%s], bci_pid = [%s], bci_timestamp = [%s], server_ip = [%s], hostname = [%s], last_connection_time_stamp = [%s]\n", app_name, nd_app_server_host, tier_name, bci_start_time, bci_pid, bci_timestamp, server_ip, hostname, last_connection_time_stamp);
  
  sprintf(ndagent_req, "nd_ctrl_msg_req:appName=%s;ndAppServerHost=%s;"
                    "tierName=%s;bciVersion= VERSION 4.2.0 BUILD 102;bciStartTime=%s;ndHome=/home/netdiagnostics;pid=%s;"
                    "BCITimeStamp=%s;serverIp=%s;hostName=%s;isAgentLess=N;jvmType=Oracle Corporation;"
                    "javaVersion=1.8.0_201;javaHome=/home/cavisson/apps/jdk1.8.0_201;machineType=LinuxEx;"
                    "supportedProtocols=TCP;requestType=1;lastConnectionTimeStamp=%s;connDuration=0;"
                    "connDestination=;\n",
                    app_name, nd_app_server_host, tier_name, bci_start_time, bci_pid, bci_timestamp, 
                    server_ip, hostname, last_connection_time_stamp);

  ns_save_string(ndagent_req, "ndagent2ndc");
  if(debug_level >= 3)
  fprintf(stdout, "\n[NDAgent->NDC] = [%s]\n", ns_eval_string("{ndagent2ndc}"));

  ns_start_transaction("NDAgentControlRegistry");

  ret_val = ns_web_websocket_send("ID=1",
                                  "BUFFER={ndagent2ndc}",
                                  "ISBINARY=0");

  ns_end_transaction("NDAgentControlRegistry", NS_AUTO_STATUS);

 if(debug_level >= 2)
  fprintf (stderr, "\nsend_control_conn_request_to_ndc [NDAGENT->NDC] return = %d\n", ret_val);

  if (ret_val !=0)
    fprintf (stderr,"\n*** Error in sending control message to ndc\n");

  return ret_val;
}

int make_data_conn_with_ndc(char *ndc_ip, char *ndc_port)
{ 
  int ret_val = -1;
  char uri[64];
  
  snprintf(uri, 64, "%s:%s", ndc_ip, ndc_port); 
  fprintf (stderr, "\n*** make_data_conn_with_ndc%s\n", uri);
  if(debug_level >= 1)
  fprintf (stderr, "\n*** message  createrd%s\n", uri);
  if(debug_level >= 1)
  fprintf(stderr,"*** ndc_ip =%s, ndc_port= %s ",ndc_ip, ndc_port);
  
  ns_save_string(uri, "ndagent2ndc");
  ns_start_transaction("NDAgentDataConnection");
  
  ret_val = ns_web_websocket_connect("ID=2",
                                         "URI=ws://{ndagent2ndc}/",
                                         "Origin=http://127.0.0.1",
                                         "Header=Accept-Language:en-us,en;q=0.5");

  ns_end_transaction("NDAgentDataConnection", NS_AUTO_STATUS);

  return ret_val;
}

int send_data_conn_request_to_ndc(int testidx, int tier_id, int server_id, int app_id, char *app_name, char *nd_app_server_host, char *tier_name, char *bci_start_time, char *bci_timestamp, char *bci_pid, char *server_ip, char *hostname, char *last_connection_time_stamp)
{
  int  ret_val = -1;
  char tx_name[128];
  char ndagent_req[1025];

  if(debug_level >= 1)
  fprintf(stderr, "**** app_name = [%s], nd_app_server_host = [%s], tier_name = [%s], bci_start_time = [%s], bci_pid = [%s], bci_timestamp = [%s], server_ip = [%s], hostname = [%s], last_connection_time_stamp = [%s], tier_id = [%d], server_id = [%d], app_id = [%d]\n", app_name, nd_app_server_host, tier_name, bci_start_time, bci_pid, bci_timestamp, server_ip, hostname, last_connection_time_stamp, tier_id, server_id, app_id);
  
  sprintf(ndagent_req, "auto_sensor_thread_hotspot_data_req:appName=%s;appID=%d;ndAppServerID=%d;ndAppServerHost=%s;tierName=%s;tierID=%d;NDCollectorIP=127.0.0.1;NDCollectorPort=7893;testIdx=%d;\n", app_name, app_id, server_id, nd_app_server_host, tier_name, tier_id, testidx); 

  ns_save_string(ndagent_req, "ndagent2ndc");
  if(debug_level >= 1)
  fprintf(stdout, "\n[NDAgent->NDC] = [%s]\n", ns_eval_string("{ndagent2ndc}"));

  ns_start_transaction("NDAgentDataRegistry");

  ret_val = ns_web_websocket_send("ID=2",
                                  "BUFFER={ndagent2ndc}",
                                  "ISBINARY=0");

  if(debug_level >= 2)
  fprintf (stdout, "\n%s[NDAGENT->NDC] return = %d\n", __FUNCTION__, ret_val);

  if (ret_val !=0){
    fprintf (stderr,"*** %s, Error in sending data connection message to ndc. Error code = %d\n", __FUNCTION__, ret_val);
    sprintf(tx_name, "NDAgentDataRegistry_%d", ret_val);
    ns_end_transaction_as("NDAgentDataRegistry", 64, tx_name);
  }
  else
    ns_end_transaction("NDAgentDataRegistry", NS_AUTO_STATUS);

  return ret_val;
}

int send_monitor_data_to_ndc_on_data_conn(gdf_data *gdf_data_struct, int total_gdf_entries, char *data, gdf_file_struct **gdf_file, int idx)
{
  gdf_file_struct *gdf_file_struct_tmp = *gdf_file + idx;
  if(debug_level >= 1) 
   fprintf (stderr," ###################### data len %d ##################",gdf_file_struct_tmp->data_len);
  int  ret_val = -1; 
  char tx_name[128];
  if(gdf_file_struct_tmp->data_len)
    ns_save_binary_val(data, "ndagent2ndc", gdf_file_struct_tmp->data_len);
  ns_start_transaction("NDAgentMonitorDataSend");
  int count = 5; 
  while(count>0)
  {
    ret_val = ns_web_websocket_send("ID=2",
                                      "BUFFER={ndagent2ndc}", 
                                      "ISBINARY=0");
    if(ret_val == 11)
    {
      count--;
      ns_page_think_time(2);
      continue;
    }
    else
      break;
  }
  
  //cmon_log_level = 0;
  if(debug_level >= 1)  
  fprintf(stdout, "\n%s, [NDAgent->DATA NDC] return = %d\n", __FUNCTION__, ret_val);

  if (ret_val !=0){
    fprintf (stderr,"*** %s Error in sending data connection message to ndc\n", __FUNCTION__);
    sprintf(tx_name, "NDAgentMonitorDataSend_%d", ret_val);
    ns_end_transaction_as("NDAgentMonitorDataSend", 64, tx_name);
  }
  else
  {
    ns_end_transaction("NDAgentMonitorDataSend", NS_AUTO_STATUS);
  }

  return ret_val;
}

int send_msg_to_ndc_on_control_connection(char *msg, char *msg_type)
{
  int  ret_val = -1;

  ns_save_string(msg, "ndagent2ndc");
  ns_start_transaction(msg_type);

  ret_val = ns_web_websocket_send("ID=1",
                                  "BUFFER={ndagent2ndc}",
                                  "ISBINARY=0");

  ns_end_transaction(msg_type, NS_AUTO_STATUS);

  if(debug_level >= 1) 
  fprintf (stdout, "\n%s, [NDAgent->NDC] msg = %s, return = %d\n", __FUNCTION__, msg, ret_val);

  if (ret_val !=0)
    fprintf (stderr,"*** Error in sending %s message to ndc\n", msg);

  return ret_val;
}

//TODO TESTIDX SET
//TODO DVM MONITOR
//TODO MONITOR STOP
//TODO BUFFER REALLOC
//TODO INTERVAL SET
//TODO HANDLING OF ALL CONFIGURATION in GDF File
//TODO GDF NOT Entry not present in gdf file
//TODO LPS MONITOR
//TODO NS_SERVER_ADMIN
//TODO LOGGING
//TODO PARSING LOGIC OPTIMIZE needs to on based of type not cm_init
//TODO RUN TIME ADD

void flow()
{
  gdf_file_struct *gdf_file = NULL; 
  char gdf_file_path[] = "/home/cavisson/TSDB_NS/workspace/admin/default/cavisson/default/default/scripts/ND_CDigest_simulation_script/GDFConfig.txt.seq";
  int max_gdf_entries = 0;
  int total_gdf_entries = 0;
  gdf_data *gdf_data_struct = NULL ;
  int idx = 0;

  char buffer[BUFF_SIZE];//Making this big as do not know how much data will be coming//TODO NEED TO REALLOC
  int resp_size = 0;    
  int ret = 0;

  int tier_id=0, server_id=0, instance_id=0;
  char nd_app_server_host[128];

  char send_monitor_data = 0;
  char create_data_conn = 1;

  int data_send_interval = 10000;//In ms /TODO fill from cm_init request and for every monitor it will be differnt
  //int data_send_interval = 6000;//In ms /TODO fill from cm_init request and for every monitor it will be differnt
  long last_time_data_sent = 0; 
  long curr_time;

  char ndc_ip[64 + 1];
  char ndc_port[8 + 1];

  ns_advance_param("ControllerIP");

  strcpy(ndc_ip, ns_eval_string("{ControllerIP}"));
  strcpy(ndc_port, ns_eval_string("{ControllerPort}"));

  char app_name[65];
  char tier_name[65];
  char bci_start_time[24];
  char bci_pid[16];
  char bci_timestamp[24];
  char server_ip[24];
  char hostname[65];
  char last_connection_time_stamp[24];
  int counter = 0;
  
  get_nd_agent_details(app_name, nd_app_server_host, tier_name, bci_start_time, bci_timestamp, bci_pid, server_ip, hostname, last_connection_time_stamp);
 
  // Connecting to WebSocket Server
  ret = make_control_conn_with_ndc(ndc_ip, ndc_port);

  if( ret != 0 )
    goto err;

  // Sending data to ndc Server for making control  connection
  ret = send_control_conn_request_to_ndc(app_name, nd_app_server_host, tier_name, bci_start_time, bci_timestamp, bci_pid, server_ip, hostname, last_connection_time_stamp);  

  if (ret !=0)
    goto err;

  int testidx = 0;
 
  //Parsing GDF File
  if (parse_gdf_file(&gdf_file, gdf_file_path, &total_gdf_entries, &max_gdf_entries ))
    goto err;

  dump_gdf_struct_info(&gdf_file, total_gdf_entries);
 
  
  /**** READ START INSTRUMENTATION MESSAGE ***/
 
  while(1)
  {
    if(send_monitor_data == 0)
    {
      while(1)
      {
        //memset(buffer,0, BUFF_SIZE);
	buffer[0] = '\0';
        resp_size = 0;
        read_msg_from_ndc_on_ctrl_conn(buffer, "MsgReadFromNDC", &resp_size);
         if(debug_level >= 1)
        {
           fprintf(stderr, "Message received [%s]\n", buffer);
           fprintf(stderr, "Response size = %d\n", resp_size);
         }
        if(strstr(buffer, "start_instrumentation"))
        {
         int ret =  parse_start_instrumentation_message(buffer, resp_size, &tier_id, &server_id, &instance_id, nd_app_server_host, gdf_file, &data_send_interval);
          if(ret == 2)
          {
           fprintf(stderr, "Going to close data connection seems like CMT test stopped ");
           goto err;
	  }
          send_monitor_data=1;
        }

        if(!resp_size)
          break;
      }
    }

    //Data conenction already created. It means already got init msg. Create data and send
    if(send_monitor_data == 1)
    {
      if(create_data_conn == 1)
      {
        ret = make_data_conn_with_ndc(ndc_ip, ndc_port); 

        if(ret != 0)
          goto err;

        ret = send_data_conn_request_to_ndc(testidx, tier_id, server_id, instance_id, app_name, nd_app_server_host, tier_name, bci_start_time, bci_timestamp, bci_pid, server_ip, hostname, last_connection_time_stamp);

        if(ret != 0)
          goto err;

        create_data_conn = 0;
	fprintf(stderr, "\n create_data_conn = %d",create_data_conn);
      }

      curr_time = ns_get_ms_stamp();
      int data_send_idx = get_interval_idx(data_send_interval);  

      if(!last_time_data_sent || ((curr_time - last_time_data_sent) >= data_send_interval))
      {
        //user can specify interval in form of samples, samples should be multiple of 10 & max should be 1200
        counter++;
        for( idx = 0 ;  idx < total_gdf_entries; idx++)
        {
          //memset(buffer, 0, BUFF_SIZE);
	  buffer[0] = '\0';
          //add additional counter in args
          make_monitor_data(gdf_data_struct, total_gdf_entries, buffer, &gdf_file, idx, tier_id, instance_id, tier_name, nd_app_server_host, app_name, counter, data_send_idx);
          
          if(debug_level >= 1)
            fprintf(stderr, "Message created is : [%s]\n", buffer);

          ret = send_monitor_data_to_ndc_on_data_conn(gdf_data_struct, total_gdf_entries, buffer, &gdf_file, idx);

          if(ret != 0)
            goto err;
        }
        //reset
        if ( counter >= 1200)
        counter = 0;
        last_time_data_sent = curr_time;
      }
    }
    ns_page_think_time(SLEEP_INTERVAL);
  }//While 

err: 
  ns_start_transaction("WebSocket_Close");
  ns_web_websocket_close("ID=1",
"CODE=1000",
"REASON=Any reson");
  ns_web_websocket_close("ID=2",
"CODE=1000",
"REASON=Any reson");
  ns_end_transaction("WebSocket_Close", NS_AUTO_STATUS);
  return;
}
